# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.33.50"
    config.vm.synced_folder ".", "/web_app", type: 'nfs'

   config.vm.provider "virtualbox" do |vb|
     vb.name = "web_app"	
  
   end
end
